import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nexus Suprimentos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>

    <html lang="pt-br">
      <body>



        {children}



      </body>
    </html>
    </>
  );
}
